// Builds the Content-Security-Policy header from the HTML actually shipped:
// every inline <script> (Next.js bootstrap payloads, the legacy account
// pages) is allowed by its SHA-256 hash, so script-src needs no
// 'unsafe-inline'. Run at image build time; writes an nginx include.
//
//   node csp-hashes.mjs <out.conf> <html files...>
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const [outFile, ...files] = process.argv.slice(2);
const hashes = new Set();
const inline = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
const CR = String.fromCharCode(13);
const LF = String.fromCharCode(10);

for (const file of files) {
  for (const m of readFileSync(file, "utf8").matchAll(inline)) {
    // Browsers hash script text AFTER the HTML parser's newline normalization
    // (CRLF and lone CR become LF), so hash the same normalized text.
    const text = m[1].split(CR + LF).join(LF).split(CR).join(LF);
    if (text.length) hashes.add(`'sha256-${createHash("sha256").update(text, "utf8").digest("base64")}'`);
  }
}

const policy = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(" ")}`,
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self' wss://$http_host",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ");

writeFileSync(outFile, `# generated by csp-hashes.mjs from ${files.length} HTML files (${hashes.size} inline scripts)` + LF +
  `add_header Content-Security-Policy "${policy}" always;` + LF);
console.log(`CSP: ${hashes.size} inline script hashes from ${files.length} files`);
