"""alerts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 11:50:54.677852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode', sa.Text(), server_default='repeat', nullable=False),
    sa.Column('cooldown_sec', sa.Integer(), server_default='300', nullable=False),
    sa.Column('channel_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('fire_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('once', 'repeat')", name=op.f('ck_alert_rules_mode_valid')),
    sa.CheckConstraint('cooldown_sec BETWEEN 10 AND 86400', name=op.f('ck_alert_rules_cooldown_range')),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 80', name=op.f('ck_alert_rules_name_length')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alert_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_alert_rules_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index('ix_alert_rules_enabled', 'alert_rules', ['enabled'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND enabled'))
    op.create_index('ix_alert_rules_owner_active', 'alert_rules', ['owner_user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('webhook')", name=op.f('ck_notification_channels_kind_valid')),
    sa.CheckConstraint('length(name) BETWEEN 1 AND 80', name=op.f('ck_notification_channels_name_length')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_notification_channels_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index('ix_notification_channels_owner_active', 'notification_channels', ['owner_user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suppressed', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_alert_events_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_events_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events')),
    sa.UniqueConstraint('rule_id', 'dedup_key', name=op.f('uq_alert_events_rule_id_dedup_key'))
    )
    op.create_index('ix_alert_events_owner_fired', 'alert_events', ['owner_user_id', sa.literal_column('fired_at DESC')], unique=False)
    op.create_index('ix_alert_events_owner_unread', 'alert_events', ['owner_user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_owner_unread', table_name='alert_events', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_alert_events_owner_fired', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_notification_channels_owner_active', table_name='notification_channels', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('notification_channels')
    op.drop_index('ix_alert_rules_owner_active', table_name='alert_rules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_alert_rules_enabled', table_name='alert_rules', postgresql_where=sa.text('deleted_at IS NULL AND enabled'))
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
